// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEwhmhcAk-4MKwDDFAJza4dPU4BB68W2Q',
    appId: '1:226347353501:web:5bfa0cf9d4e8f74cc4db74',
    messagingSenderId: '226347353501',
    projectId: 'travel-demo-fa813',
    authDomain: 'travel-demo-fa813.firebaseapp.com',
    storageBucket: 'travel-demo-fa813.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvvLYr5ZaXMd2PCr33aYk_J_MvWyI5x8w',
    appId: '1:226347353501:android:30cff8dfd06fc620c4db74',
    messagingSenderId: '226347353501',
    projectId: 'travel-demo-fa813',
    storageBucket: 'travel-demo-fa813.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPqBpwpexdC4e6pr7Fs-pT7YMGHBi9W6Q',
    appId: '1:226347353501:ios:d7ca8261f6dcabc6c4db74',
    messagingSenderId: '226347353501',
    projectId: 'travel-demo-fa813',
    storageBucket: 'travel-demo-fa813.firebasestorage.app',
    iosBundleId: 'com.anytime.travel',
  );
}
