run:
  timeout: 5m

issues:
  exclude-files:
    - "scripts/.*\\.go$"
    - "seeds/.*\\.go$"
  exclude-dirs:
    - scripts
    - seeds
    - tmp
    - build
    - bin

linters:
  disable-all: true
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck

linters-settings:
  govet:
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - composites
      - copylocks
    disable:
      - shadow
