run:
  timeout: 5m
  skip-dirs:
    - scripts
    - seeds
    - tmp
    - build
    - bin

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck

linters-settings:
  govet:
    check-shadowing: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: scripts/
      linters:
        - typecheck
    - path: seeds/
      linters:
        - typecheck
    - text: "could not import.*seeds"
      linters:
        - typecheck
